[versions]
intellij = "1.3.1"
kotlin = "1.6.10"

[plugins]
intellij = { id = "org.jetbrains.intellij", version.ref = "intellij" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
