name: Bug report
description: Create a bug report to help us improve
title: ""
labels:
  - "bug"
assignees:
  - t28hub
body:
  - type: markdown
    attributes:
      value: "Thank you for reporting your bug."
  - type: input
    id: short-description
    attributes:
      label: Short description
      description: Describe the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: json
    attributes:
      label: JSON or JSON Schema
      description: Attach a JSON or JSON Schema to reproduce this bug if possible.
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe expected behavior.
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Describe your environemnt.
      value: |
        - IDE version:
          - e.g. IntelliJ IDEA 2021.2.3 (Ultimate Edition)
        - OS version:
          - e.g. macOS Monterey 12.0.1
        - Other relevant context:
    validations:
      required: true
